#!/bin/bash
BUILDFOLDER="appbuild"
MAIN=PedlMon

mkdir -p $BUILDFOLDER
for f in *.py ; do
    cp -r $f $BUILDFOLDER/
done
for folder in assets ; do
    cp -r $folder $BUILDFOLDER/
done

pushd $BUILDFOLDER
mv oscmonitor.py $MAIN.py
rm setup.py
py2applet --make-setup $MAIN.py assets/icon.icns
python setup.py py2app
popd

rm -fr $BUILDFOLDER/dist/$MAIN.app/Contents/Frameworks/Tcl.framework/Versions/8.5/Resources/English.lproj/ActiveTcl-8.5

mv $BUILDFOLDER/dist/*.app ./
