#!/bin/bash
if [ -z $VIRTUAL_ENV ] ; then
	echo ------------------------------------------------
	echo  This script must be called withit a virtualenv
	echo ------------------------------------------------
	echo
	exit 1
fi

BUILDFOLDER="appbuild"
ENTRY='Pedlbrd'

mkdir -p $BUILDFOLDER

for folder in pedlbrd assets; do
	cp -r $folder $BUILDFOLDER/
done

cp $ENTRY.py $BUILDFOLDER

cd $BUILDFOLDER
py2applet --make-setup Pedlbrd.py assets/pedlbrd-icon.icns
python setup.py py2app
cd ..

echo "The app is at $BUILDFOLDER/dist/$ENTRY.app"

open "$BUILDFOLDER/dist/$ENTRY.app"
