#!/bin/bash
if [ -z $VIRTUAL_ENV ] ; then
	echo ------------------------------------------------
	echo  This script must be called within a virtualenv
	echo ------------------------------------------------
	echo
	exit
fi

function usage() {
	echo "Makes the Pedlbrd.app"
	echo "Usage: $(basename $0) [options]"
	echo "Options:"
	echo "  --package"
	echo "      Create a .dmg for distribution" 
	echo "  --dmg"
	echo "      Create a .dmg of only the app"
	echo "  --skip"
	echo "      Skip building the app. Implies --package"
	echo "  --midimonitor"
	echo "      Do not include MIDI Monitor in the built DMG"
	echo "  --dirty"
	echo "      Dont clean up after building .dmg"
	echo "  --debug-dmg"
	echo "      Create a .dmg fast, avoiding building and copying the app"
	echo "  --fat"
	echo "      Do not eliminate unused files from app"
}

# -------------------------
#       Parse Options
# -------------------------
CREATEPACKAGE=0
OPENAPPFOLDER=1
BUILDAPP=1
MIDIMONITOR=0
COPYAPP=1
CLEANUP=1
REMOVE_UNUSED_FILES=0
PD=1

while test "${1:0:1}" = "-"; do
	case $1 in
	    --help)
		    usage
		    exit;;
	    --package)
		    CREATEPACKAGE=1
		    SIMPLEDMG=0
		    OPENAPPFOLDER=0
		    shift;;
		--dmg)
			SIMPLEDMG=1
			CREATEPACKAGE=0
			OPENAPPFOLDER=0
			shift;;
	    --skip)
		    BUILDAPP=0
		    CREATEPACKAGE=1
		    shift;;
		--debug-dmg)
		    BUILDAPP=0
			CREATEPACKAGE=1
			COPYAPP=0
			shift;;
		--dirty)
			CLEANUP=0
			shift;;
		--midimonitor)
			MIDIMONITOR=1
			shift;;
      	--fat)
			REMOVE_UNUSED_FILES=0
			shift;;
	esac
done

function showoption() {
	# value, msg
	if [ $1 == 1 ] ; then
		echo "[x] $2"
	else
		echo "[ ] $2"
	fi
}

echo "---------------------------"
showoption $BUILDAPP      "build app"
showoption $CREATEPACKAGE "create dmg"
showoption $SIMPLEDMG     "pack the app in a dmg file, no fancy packaging"
showoption $CLEANUP       "clean garbage"
showoption $REMOVE_UNUSED_FILES "remove unused files"
showoption $PD "include PD control panel"
echo "---------------------------"
echo

# ------------
#  Build app
# ------------

BUILDFOLDER="appbuild"
ENTRY='Pedlbrd'
ICONSIZE=128
EXCLUDES="cython,test,pip,Finder"

if [ $BUILDAPP == 1 ]; then
	echo "<< building app >>"
	mkdir -p $BUILDFOLDER

	rm -f $BUILDFOLDER/setup.py

	for f in pedlbrd pedltalk.py assets oscmonitor.py firmware; do
		cp -r $f $BUILDFOLDER/
	done

	if [ $PD == 1 ]; then
		mkdir -p $BUILDFOLDER/extra
		mkdir -p $BUILDFOLDER/extra/pd
		cp extra/pd/*.pd $BUILDFOLDER/extra/pd
	fi

	cp -f $ENTRY.py $BUILDFOLDER

	pushd $BUILDFOLDER
	py2applet --make-setup Pedlbrd.py pedltalk.py oscmonitor.py assets/pedlbrd-icon.icns
	python setup.py py2app -e $EXCLUDES --resources extra,assets,firmware
	popd

	if [ $REMOVE_UNUSED_FILES == 1 ]; then
		echo "<< removing unused files >>"
		rm -fr $BUILDFOLDER/dist/$ENTRY.app/Contents/Frameworks/Tcl.framework/Versions/8.5/Resources/English.lproj/ActiveTcl-8.5
		for package in Cython pyexpat.so _codecs_jp.so _codecs_cn.so _codecs_hk.so; do
			rm -fr $BUILDFOLDER/dist/$ENTRY.app/Contents/Resources/lib/python2.7/lib-dynload/$package
		done

	fi
	
	echo "The app is at $BUILDFOLDER/dist/$ENTRY.app"

	if [ $OPENAPPFOLDER == 1 ]; then
		open "$BUILDFOLDER/dist"
	fi
fi

# -----------------
#    Create DMG
# -----------------

if [[ $SIMPLEDMG == 1 ]]; then
	rm -f $PACKAGE
	mkdir -p $BUILDFOLDER/package
	if [[ $COPYAPP == 1 ]]; then
		echo "   * copying app"
		cp -r $BUILDFOLDER/dist/$ENTRY.app $BUILDFOLDER/package
		echo "creating DMG"
		hdiutil create -volname $ENTRY -srcfolder $BUILDFOLDER/package -ov -format UDZO $ENTRY.dmg
		echo "moving DMG to binaries"
		rm -f binaries/$ENTRY.dmg
		mv $ENTRY.dmg binaries/$ENTRY.dmg
	fi
fi

if [ $CREATEPACKAGE == 1 ]; then
	X0=32
	Y0=32
	MARGINX=32
	MARGINY=48
	PACKAGE=$ENTRY.dmg
	APPFOLDERX=$(( ($ICONSIZE + $MARGINX)*3 ))

	echo "<< creating .dmg package >>"
	rm -f $PACKAGE
	mkdir -p $BUILDFOLDER/package
	if [ $COPYAPP == 1 ] ; then
		echo "   * copying app"
		cp -r $BUILDFOLDER/dist/$ENTRY.app $BUILDFOLDER/package
	fi
	if [ $MIDIMONITOR == 1 ]; then
		echo "   * copying MIDI Monitor"
		cp -r "extra/OSX/MIDI Monitor.app" $BUILDFOLDER/package
	fi
	cp extra/OSX/README.txt $BUILDFOLDER/package

	echo "   * creating dmg"
	extra/OSX/yoursway-create-dmg/create-dmg \
		--window-size $(( $APPFOLDERX + $ICONSIZE + $X0 )) $(( $ICONSIZE * 3 )) \
		--volname $ENTRY --icon-size $ICONSIZE \
		--icon $ENTRY.app $X0 $Y0 --app-drop-link $APPFOLDERX $Y0 \
		--icon MIDI\ Monitor.app $(($X0 + $ICONSIZE + $MARGINX)) $Y0 \
		--icon README.txt $X0 $(( $Y0 + $ICONSIZE + $MARGINY)) \
		$PACKAGE $BUILDFOLDER/package

	# if package exists, build was successful. Move to the dist folder, else raise error
	if [ -e $PACKAGE ] ; then
		rm -f $BUILDFOLDER/dist/$PACKAGE
		mv $PACKAGE $BUILDFOLDER/dist
		open $BUILDFOLDER/dist
		if [ CLEANUP == 1 ] ; then
			echo "<< removing build files for .dmg package >>"
			rm -fr $BUIDFOLDER/package
		fi
	else
		echo "### ERROR: .dmg package not created!"
		exit
	fi
fi
